/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExtensionsRouteRouteImport } from './routes/extensions/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionsDiceRouteImport } from './routes/extensions/dice'
import { Route as ExtensionsSheetSheetIdRouteImport } from './routes/extensions/sheet/$sheetId'

const ExtensionsRouteRoute = ExtensionsRouteRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsDiceRoute = ExtensionsDiceRouteImport.update({
  id: '/dice',
  path: '/dice',
  getParentRoute: () => ExtensionsRouteRoute,
} as any)
const ExtensionsSheetSheetIdRoute = ExtensionsSheetSheetIdRouteImport.update({
  id: '/sheet/$sheetId',
  path: '/sheet/$sheetId',
  getParentRoute: () => ExtensionsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRouteRouteWithChildren
  '/extensions/dice': typeof ExtensionsDiceRoute
  '/extensions/sheet/$sheetId': typeof ExtensionsSheetSheetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRouteRouteWithChildren
  '/extensions/dice': typeof ExtensionsDiceRoute
  '/extensions/sheet/$sheetId': typeof ExtensionsSheetSheetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRouteRouteWithChildren
  '/extensions/dice': typeof ExtensionsDiceRoute
  '/extensions/sheet/$sheetId': typeof ExtensionsSheetSheetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extensions'
    | '/extensions/dice'
    | '/extensions/sheet/$sheetId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/extensions' | '/extensions/dice' | '/extensions/sheet/$sheetId'
  id:
    | '__root__'
    | '/'
    | '/extensions'
    | '/extensions/dice'
    | '/extensions/sheet/$sheetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionsRouteRoute: typeof ExtensionsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/dice': {
      id: '/extensions/dice'
      path: '/dice'
      fullPath: '/extensions/dice'
      preLoaderRoute: typeof ExtensionsDiceRouteImport
      parentRoute: typeof ExtensionsRouteRoute
    }
    '/extensions/sheet/$sheetId': {
      id: '/extensions/sheet/$sheetId'
      path: '/sheet/$sheetId'
      fullPath: '/extensions/sheet/$sheetId'
      preLoaderRoute: typeof ExtensionsSheetSheetIdRouteImport
      parentRoute: typeof ExtensionsRouteRoute
    }
  }
}

interface ExtensionsRouteRouteChildren {
  ExtensionsDiceRoute: typeof ExtensionsDiceRoute
  ExtensionsSheetSheetIdRoute: typeof ExtensionsSheetSheetIdRoute
}

const ExtensionsRouteRouteChildren: ExtensionsRouteRouteChildren = {
  ExtensionsDiceRoute: ExtensionsDiceRoute,
  ExtensionsSheetSheetIdRoute: ExtensionsSheetSheetIdRoute,
}

const ExtensionsRouteRouteWithChildren = ExtensionsRouteRoute._addFileChildren(
  ExtensionsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionsRouteRoute: ExtensionsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
