/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SheetRouteRouteImport } from './routes/sheet/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SheetSheetIdRouteImport } from './routes/sheet/$sheetId'

const SheetRouteRoute = SheetRouteRouteImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetSheetIdRoute = SheetSheetIdRouteImport.update({
  id: '/$sheetId',
  path: '/$sheetId',
  getParentRoute: () => SheetRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sheet': typeof SheetRouteRouteWithChildren
  '/sheet/$sheetId': typeof SheetSheetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sheet': typeof SheetRouteRouteWithChildren
  '/sheet/$sheetId': typeof SheetSheetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sheet': typeof SheetRouteRouteWithChildren
  '/sheet/$sheetId': typeof SheetSheetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sheet' | '/sheet/$sheetId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sheet' | '/sheet/$sheetId'
  id: '__root__' | '/' | '/sheet' | '/sheet/$sheetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SheetRouteRoute: typeof SheetRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sheet': {
      id: '/sheet'
      path: '/sheet'
      fullPath: '/sheet'
      preLoaderRoute: typeof SheetRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/$sheetId': {
      id: '/sheet/$sheetId'
      path: '/$sheetId'
      fullPath: '/sheet/$sheetId'
      preLoaderRoute: typeof SheetSheetIdRouteImport
      parentRoute: typeof SheetRouteRoute
    }
  }
}

interface SheetRouteRouteChildren {
  SheetSheetIdRoute: typeof SheetSheetIdRoute
}

const SheetRouteRouteChildren: SheetRouteRouteChildren = {
  SheetSheetIdRoute: SheetSheetIdRoute,
}

const SheetRouteRouteWithChildren = SheetRouteRoute._addFileChildren(
  SheetRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SheetRouteRoute: SheetRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
